export const shares = [
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.lHsqpjguR6av3vOrDmbcIQAAAA?rs=1&pid=ImgDetMain",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "InonG Share ",
    subtitle: "Stock-Market First-Share",
    web: "www.fsgsf.co.il",
    description: "01Share",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [500, 555],
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.lHsqpjguR6av3vOrDmbcIQAAAA?rs=1&pid=ImgDetMain",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "HackerU Share ",
    subtitle: "Stock-Market Second-Share",
    web: "www.fsgsf.co.il",
    description: "02Share",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [480, 500],
    bizNumber: 95916302329,
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.lHsqpjguR6av3vOrDmbcIQAAAA?rs=1&pid=ImgDetMain",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "HackerU Full-Stack ",
    subtitle: "Stock-Market 3th-Share",
    web: "www.fsgsf.co.il",
    description: "03Share",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [200, 220],
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.DBB0DhM2FhWbi092INutmwHaEF?w=322&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "Bank Of America",
    subtitle: "Americans Bank",
    web: "www.fsgsf.co.il",
    description: "the offical bank of America",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [250, 240],
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.WG1MTFyO-zXiLY9kLm8BAgHaE7?w=234&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "Bank Of Israel",
    subtitle: "Israeli Bank",
    web: "www.fsgsf.co.il",
    description: "the offical bank of Israel",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [300, 290],
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.Hm514fyz4isZbnZXGASMawHaEP?w=300&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "Bank Of Russia",
    subtitle: "Russian bank",
    web: "www.fsgsf.co.il",
    description: "the offical bank of Russia",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [350, 370],
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.IdsfknFFjjrSBPa8HDNcjQHaEo?w=291&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "Ford Cars",
    subtitle: "Ford comapny",
    web: "www.fsgsf.co.il",
    description: "cars and more",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [220, 210],
  },
  {
    address: {
      city: "Anytown",
      state: "",
      country: "Israel",
      street: "123 Main St",
      zip: "12345",
      houseNumber: 20,
    },
    image: {
      url: "https://th.bing.com/th/id/OIP.2ihy77Ox68M5_JTSu7aZMAHaHa?w=216&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      alt: "user-profile",
    },
    phone: "050-8123091",
    email: "admin@gmail.com",
    title: "BMW Cars",
    subtitle: "BMW comapny",
    web: "www.fsgsf.co.il",
    description: "cars and more",
    userId: "657f4929ac0fc8034c774bea",
    owners: [],
    price: [220, 210],
  },
];
